import Input from '../form/input';

const formValues = [
  {
    contentName: 'drugName',
    contentLabel: 'Name',
    contentType: 'text',
    contentAlt: '',
    contentOptions: null,
    contentHelp: '',
    component: Input,
    page: 1,
    onSubmit: 'nextPage',
    submitLabel: 'Next',
    auxButtonLabel: false,
  },
  {
    contentName: 'drugDosage',
    contentLabel: 'Dosage',
    contentType: 'text',
    contentAlt: '',
    contentOptions: ['10mg', '20mg', '30mg', '40mg'],
    contentHelp: '',
    component: Input,
    page: 2,
    onSubmit: 'nextPage',
    submitLabel: 'Next',
    auxButton: 'previousPage',
    auxButtonLabel: 'Back',
  },
  {
    contentName: 'drugForm',
    contentLabel: 'Form',
    contentType: 'text',
    contentAlt: '',
    contentOptions: ['Capsule', 'Liquid'],
    contentHelp: '',
    component: Input,
    page: 3,
    onSubmit: 'nextPage',
    submitLabel: 'Next',
    auxButton: 'previousPage',
    auxButtonLabel: 'Back',
  },
  {
    contentName: 'drugUseGeneric',
    contentLabel: 'Include Generic',
    contentType: 'checkbox',
    contentOptions: ['No Generics','Generic'],
    contentHelp: '',
    component: Input,
    page: 4,
    onSubmit: 'nextPage',
    submitLabel: 'Next',
    auxButton: 'previousPage',
    auxButtonLabel: 'Back',
  },
  {
    contentName: 'drugUseBranded',
    contentLabel: 'Include Brands',
    contentType: 'checkbox',
    contentOptions: ['No Brands', 'Brands'],
    contentHelp: '',
    component: Input,
    page: 5,
    onSubmit: 'nextPage',
    submitLabel: 'Next',
    auxButton: 'previousPage',
    auxButtonLabel: 'Back',
  },
  {
    contentName: 'drugQuantity',
    contentLabel: 'Quantity',
    contentType: 'text',
    contentAlt: '',
    contentOptions: null,
    contentHelp: '',
    component: Input,
    page: 6,
    onSubmit: 'nextPage',
    submitLabel: 'Next',
    auxButton: 'previousPage',
    auxButtonLabel: 'Back',
  },
];

export default formValues;
